
spring:
  application:
    name: aws
  jmx:
    enabled: false
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./target/h2db/db/access
    driverClassName: org.h2.Driver
    username: access
    password:
    database-platform: org.hibernate.dialect.H2Dialect

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 8085





