spring:
  application:
    name: aws
  jmx:
    enabled: false
  datasource:
    url: jdbc:postgresql://postgres.cluster-cslje4xnrbex.us-west-2.rds.amazonaws.com:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 12345678
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
    database-platform: com.epam.subo.util.domain.FixedPostgreSql95Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 8085





